/// Flutter icons GeemIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  GeemIcons
///      fonts:
///       - asset: fonts/GeemIcons.ttf
///
///
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

class GeemIcons {
  GeemIcons._();

  static const _kFontFam = 'GeemIcons';
  static const String? _kFontPkg = null;

  static const IconData droplet =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drizzle =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_flash =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_wind =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rain =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_sun =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_1 =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_open_mini =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location =
      IconData(0xf031, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_alt =
      IconData(0xf073, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud =
      IconData(0xf0c2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left =
      IconData(0xf177, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_moon =
      IconData(0xf6c3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloudy_sun =
      IconData(0xf6c4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wind =
      IconData(0xf72e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_moon_rain =
      IconData(0xf73c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_rain =
      IconData(0xf73d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_showers_heavy =
      IconData(0xf740, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_sun_rain =
      IconData(0xf743, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
